import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import OffersCarousel from "./components/offerscarousel";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
   <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
  
  {/* Top centered title */}
  <div className="w-full text-center py-3 bg-[#e5ad2c] text-5xl font-bold tracking-wide text-white">
     <span className="text-[white]">Sri Lakshmi Durga</span>
  </div>

  <Navbar />
  <OffersCarousel />

  
  {children}
</body>


    </html>
  );
}
